### ISSUE TITLE
Test 01/07 - NREs

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#143]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.PlayerPawn.IsOutlineVisible() in Player/PlayerController/PlayerPawn.Effects.cs:line 47
   at Facepunch.PlayerPawn.UpdateOutline() in Player/PlayerController/PlayerPawn.Effects.cs:line 58
   at Facepunch.PlayerPawn.OnFixedUpdate() in Player/PlayerController/PlayerPawn.cs:line 131
   at Sandbox.Component.ExceptionWrap(String name, Action a)
```

Getting error spam here
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.GameUtils.<>c__DisplayClass5_0.<GetPlayerPawns>b__0(PlayerPawn x) in GameMode/GameUtils.cs:line 27
   at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)
   at PlayerColors.GetColor(PlayerPawn player) in Player/PlayerColors.cs:line 38
   at Facepunch.PlayerPawn.get_PlayerColor() in Player/PlayerController/PlayerPawn.Pawn.cs:line 20
   at Facepunch.PlayerPawn.UpdateOutline() in Player/PlayerController/PlayerPawn.Effects.cs:line 71
   at Facepunch.PlayerPawn.OnFixedUpdate() in Player/PlayerController/PlayerPawn.cs:line 131
   at Sandbox.Component.ExceptionWrap(String name, Action a)
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.PlayerPawn.get_BodyRenderer() in Player/PlayerController/PlayerPawn.cs:line 64
   at Facepunch.ShootWeaponComponent.<DoShootEffects>b__98_0() in Weapons/Components/ShootWeaponComponent.cs:line 156
   at Sandbox.Rpc.Resume(WrappedMethod m)
   at Sandbox.Component.__rpc_Broadcast(WrappedMethod m, Object[] argumentList)
   at Facepunch.ShootWeaponComponent.DoShootEffects() in Weapons/Components/ShootWeaponComponent.cs:line 115
   at InvokeStub_ShootWeaponComponent.DoShootEffects(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Component.get_Tags()
   at Facepunch.AimWeaponComponent.CanAim() in Weapons/Components/AimWeaponComponent.cs:line 23
   at Facepunch.AimWeaponComponent.OnUpdate() in Weapons/Components/AimWeaponComponent.cs:line 30
   at Sandbox.Component.ExceptionWrap(String name, Action a)
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.PlayerPawn.get_BodyRenderer() in Player/PlayerController/PlayerPawn.cs:line 64
   at Facepunch.ShootWeaponComponent.<DoShootEffects>b__98_0() in Weapons/Components/ShootWeaponComponent.cs:line 156
   at Sandbox.Rpc.Resume(WrappedMethod m)
   at Sandbox.Component.__rpc_Broadcast(WrappedMethod m, Object[] argumentList)
   at Facepunch.ShootWeaponComponent.DoShootEffects() in Weapons/Components/ShootWeaponComponent.cs:line 115
   at InvokeStub_ShootWeaponComponent.DoShootEffects(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.PlayerMarker.get_IsEnemy() in Player/PlayerMarker.cs:line 85
   at Facepunch.PlayerMarker.Facepunch.IMinimapIcon.get_IconPath() in Player/PlayerMarker.cs:line 48
   at Facepunch.Minimap.BuildRenderTree(RenderTreeBuilder __builder) in UI/HUD/Minimap/Minimap.razor:line 34
   at Sandbox.UI.Panel.InternalRenderTree()
```

**Comment by Metapyziks** [comment]
My log was completely filled with this one during the test.
```
Error calculating hash on Facepunch.UI.PlayerAvatar - Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.PlayerState.get_PlayerPawn() in Player/PawnSystem/PlayerState.cs:line 76
   at Facepunch.UI.PlayerAvatar.BuildHash() in UI/HUD/Components/PlayerAvatar.razor:line 60
   at Sandbox.UI.Panel.InternalTreeBinds()
```
