### ISSUE TITLE
Most common NREs and Bugs

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#150]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.PlayerPawn.get_BodyRenderer() in Player/PlayerController/PlayerPawn.cs:line 64
   at Facepunch.ReloadWeaponComponent.<CancelReload>b__32_0() in Weapons/Components/ReloadWeaponComponent.cs:line 115
   at Sandbox.Rpc.Resume(WrappedMethod m)
   at Sandbox.Component.__rpc_Broadcast(WrappedMethod m, Object[] argumentList)
   at Facepunch.ReloadWeaponComponent.CancelReload() in Weapons/Components/ReloadWeaponComponent.cs:line 111
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.PlayerPawn.get_BodyRenderer() in Player/PlayerController/PlayerPawn.cs:line 64
   at Facepunch.ShootWeaponComponent.<DoShootEffects>b__98_0() in Weapons/Components/ShootWeaponComponent.cs:line 156
   at Sandbox.Rpc.Resume(WrappedMethod m)
   at Sandbox.Component.__rpc_Broadcast(WrappedMethod m, Object[] argumentList)
   at Facepunch.ShootWeaponComponent.DoShootEffects() in Weapons/Components/ShootWeaponComponent.cs:line 115
   at InvokeStub_ShootWeaponComponent.DoShootEffects(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.PlayerState.get_PlayerPawn() in Player/PawnSystem/PlayerState.cs:line 82
   at Facepunch.UI.PlayerAvatar.BuildHash() in UI/HUD/Components/PlayerAvatar.razor:line 62
   at Sandbox.UI.Panel.InternalTreeBinds()
```

Add more if you have them!

**Comment by Metapyziks** [comment]
```
2024/07/02 15:03:52.1539	[Generic] Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.PlayerFootsteps.OnEvent(FootstepEvent e) in Player/PlayerFootsteps.cs:line 60
   at Sandbox.SkinnedModelRenderer.InternalOnFootstep(FootstepEvent e)
   at Sandbox.SceneModel.OnAnimationEvent(IntPtr typeName, Single cycle, Single time, IntPtr data)
```

**Comment by DevulTj** [comment]
```
2024/07/05 07:15:34.9040	[GameMenu] Exception when calling 'FixedUpdate' on PlayerPawn on (Player (ziks))	System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.PlayerPawn.IsOutlineVisible() in Player/PlayerController/PlayerPawn.Effects.cs:line 50
   at Facepunch.PlayerPawn.UpdateOutline() in Player/PlayerController/PlayerPawn.Effects.cs:line 62
   at Facepunch.PlayerPawn.OnFixedUpdate() in Player/PlayerController/PlayerPawn.cs:line 142
   at Sandbox.Component.ExceptionWrap(String name, Action a)
```

```
2024/07/05 07:15:35.2153	[GameMenu] Error calculating hash on Sandbox.<PanelComponent>FA1C5275512F4A92FD662E1A2B690E382292D174E8B798CBA2E5730251CFA55D7__CustomBuildPanel - Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.UI.MainHUD.BuildHash() in UI/HUD/MainHUD.razor:line 82
   at Sandbox.PanelComponent.BuildRenderHash()
   at Sandbox.<PanelComponent>FA1C5275512F4A92FD662E1A2B690E382292D174E8B798CBA2E5730251CFA55D7__CustomBuildPanel.BuildHash()
   at Sandbox.UI.Panel.InternalTreeBinds()
```

```
2024/07/05 07:15:42.3496	[GameMenu] Exception when calling 'FixedUpdate' on PlayerPawn on (Player (ziks))	System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.GameUtils.<>c__DisplayClass5_0.<GetPlayerPawns>b__0(PlayerPawn x) in GameMode/GameUtils.cs:line 34
   at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)
   at PlayerColors.GetColor(PlayerState player) in Player/PlayerColors.cs:line 34
   at Facepunch.PlayerState.get_PlayerColor() in Player/PawnSystem/PlayerState.cs:line 75
   at Facepunch.PlayerPawn.UpdateOutline() in Player/PlayerController/PlayerPawn.Effects.cs:line 75
   at Facepunch.PlayerPawn.OnFixedUpdate() in Player/PlayerController/PlayerPawn.cs:line 142
   at Sandbox.Component.ExceptionWrap(String name, Action a)
```

```
2024/07/05 07:15:42.4218	[GameMenu] Error when building render tree on Facepunch.UI.PlayerMarkerPanel - Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.TeamExtensions.IsFriendly(PlayerPawn self, PlayerPawn other) in Player/TeamComponent.cs:line 78
   at Facepunch.UI.PlayerMarkerPanel.get_PersonalColor() in UI/MarkerSystem/MarkerTypes/PlayerMarkerPanel.razor:line 122
   at Facepunch.UI.PlayerMarkerPanel.BuildRenderTree(RenderTreeBuilder __builder) in UI/MarkerSystem/MarkerTypes/PlayerMarkerPanel.razor:line 6
   at Sandbox.UI.Panel.InternalRenderTree()
```
